/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHRONOS_H_RPCGEN
#define _CHRONOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct chronos_in {
	int tm_sec;
	int tm_min;
	int tm_hour;
	int tm_mday;
	int tm_mon;
	int tm_year;
	int tm_wday;
	int tm_yday;
	int tm_isdst;
};
typedef struct chronos_in chronos_in;

struct chronos_out {
	int tm_sec;
	int tm_min;
	int tm_hour;
	int tm_mday;
	int tm_mon;
	int tm_year;
	int tm_wday;
	int tm_yday;
	int tm_isdst;
	long tm_ms;
	float process_delay;
};
typedef struct chronos_out chronos_out;

#define chronos_PROG 0x31230000
#define chronos_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define chronosPROC 1
extern  chronos_out * chronosproc_1(chronos_in *, CLIENT *);
extern  chronos_out * chronosproc_1_svc(chronos_in *, struct svc_req *);
extern int chronos_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define chronosPROC 1
extern  chronos_out * chronosproc_1();
extern  chronos_out * chronosproc_1_svc();
extern int chronos_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_chronos_in (XDR *, chronos_in*);
extern  bool_t xdr_chronos_out (XDR *, chronos_out*);

#else /* K&R C */
extern bool_t xdr_chronos_in ();
extern bool_t xdr_chronos_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHRONOS_H_RPCGEN */
