/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "chronos.h"

bool_t
xdr_chronos_in (XDR *xdrs, chronos_in *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 9 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->tm_sec))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_min))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_hour))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_mday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_mon))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_year))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_wday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_yday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_isdst))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->tm_sec);
			IXDR_PUT_LONG(buf, objp->tm_min);
			IXDR_PUT_LONG(buf, objp->tm_hour);
			IXDR_PUT_LONG(buf, objp->tm_mday);
			IXDR_PUT_LONG(buf, objp->tm_mon);
			IXDR_PUT_LONG(buf, objp->tm_year);
			IXDR_PUT_LONG(buf, objp->tm_wday);
			IXDR_PUT_LONG(buf, objp->tm_yday);
			IXDR_PUT_LONG(buf, objp->tm_isdst);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 9 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->tm_sec))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_min))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_hour))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_mday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_mon))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_year))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_wday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_yday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_isdst))
				 return FALSE;
		} else {
			objp->tm_sec = IXDR_GET_LONG(buf);
			objp->tm_min = IXDR_GET_LONG(buf);
			objp->tm_hour = IXDR_GET_LONG(buf);
			objp->tm_mday = IXDR_GET_LONG(buf);
			objp->tm_mon = IXDR_GET_LONG(buf);
			objp->tm_year = IXDR_GET_LONG(buf);
			objp->tm_wday = IXDR_GET_LONG(buf);
			objp->tm_yday = IXDR_GET_LONG(buf);
			objp->tm_isdst = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->tm_sec))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_hour))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_mday))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_mon))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_year))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_wday))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_yday))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_isdst))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_chronos_out (XDR *xdrs, chronos_out *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->tm_sec))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_min))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_hour))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_mday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_mon))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_year))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_wday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_yday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_isdst))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->tm_ms))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->tm_sec);
		IXDR_PUT_LONG(buf, objp->tm_min);
		IXDR_PUT_LONG(buf, objp->tm_hour);
		IXDR_PUT_LONG(buf, objp->tm_mday);
		IXDR_PUT_LONG(buf, objp->tm_mon);
		IXDR_PUT_LONG(buf, objp->tm_year);
		IXDR_PUT_LONG(buf, objp->tm_wday);
		IXDR_PUT_LONG(buf, objp->tm_yday);
		IXDR_PUT_LONG(buf, objp->tm_isdst);
		IXDR_PUT_LONG(buf, objp->tm_ms);
		}
		 if (!xdr_float (xdrs, &objp->process_delay))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->tm_sec))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_min))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_hour))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_mday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_mon))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_year))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_wday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_yday))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->tm_isdst))
				 return FALSE;
			 if (!xdr_long (xdrs, &objp->tm_ms))
				 return FALSE;

		} else {
		objp->tm_sec = IXDR_GET_LONG(buf);
		objp->tm_min = IXDR_GET_LONG(buf);
		objp->tm_hour = IXDR_GET_LONG(buf);
		objp->tm_mday = IXDR_GET_LONG(buf);
		objp->tm_mon = IXDR_GET_LONG(buf);
		objp->tm_year = IXDR_GET_LONG(buf);
		objp->tm_wday = IXDR_GET_LONG(buf);
		objp->tm_yday = IXDR_GET_LONG(buf);
		objp->tm_isdst = IXDR_GET_LONG(buf);
		objp->tm_ms = IXDR_GET_LONG(buf);
		}
		 if (!xdr_float (xdrs, &objp->process_delay))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->tm_sec))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_hour))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_mday))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_mon))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_year))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_wday))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_yday))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tm_isdst))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->tm_ms))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->process_delay))
		 return FALSE;
	return TRUE;
}
